### ISSUE TITLE
Create and emit events for verify() 

### ISSUE THREAD

**Issue by zintarh** [nexlabsweb3/scanguard#5]
This issues is part of ODHACK 9.0, apply via the platform

Thank you for showing interest!

Ensure that relevant data is captured in the events

Depends on #3

**Please ensure to provide an ETA.**

Looking forward to seeing your great work!

**Comment by MullerTheScientist** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
I am a full-stack developer with experience in QA testing and languages like Python, Cairo, Solidity, React, and JavaScript.

### How I plan on tackling this issue
i will Add event emission to the verify_product() function.
Create a new ProductVerified event instance with the relevant data.

**Comment by ptisserand** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
I'm a senior cairo developer with strong experience in Starknet ecosystem (since cairo 0). I have contributed to several projects on Only Dust writing smart contract code or rust backend.

### How I plan on tackling this issue
After added event struct definition in smart contract, I will ensure that events are emitted through starknet foundry tests 
ETA: 0.5 day

**Comment by No-bodyq** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
I am a web3 dev with experience writing smart contracts in cairo: Here is my onlydust Profile: https://app.onlydust.com/u/No-bodyq

### How I plan on tackling this issue
I will create a struct that derives from the starknet event trait and add the data fields to be be emitted with the event, add the event to an event enum then ensure it is properly emitted when the function is called
ETA: < 1 day

**Comment by Pvsaint** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
I'm Victor Peter, a front-end and smart contract developer with about 3 years experience in react

### How I plan on tackling this issue
I'll need to define the event that will be emitted when the verify_product() function is called. This can be done using the events property in the smart contract.
Then I need to create a function that will emit the event when the verify_product() function is called. This can be done using the emit keyword in the smart contract.
Finally, I need to call the function that emits the event when the verify_product() function is called.

**Comment by manlikeHB** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
Hi, I am a skilled Cairo dev with lots of experience contributing to amazing projects, my profile is a witness to that statement.

### How I plan on tackling this issue
I'll create the function with the expected functionality and full test coverage.
ETA- 2days

**Comment by ptisserand** [comment]
Hi @zintarh I think there is a dependency between this issue and #3 , I think they are breaking changes for event testing between starknet-foundry 0.25.0 and 0.32.0

**Comment by saimeunt** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
I have contributed to several Cairo projects on OnlyDust and I've worked on very similar issues in the past such as https://github.com/ArkProjectNFTs/bridge/pull/236

### How I plan on tackling this issue
I will carefully add the necessary Starknet event and will make sure to emit it correctly where it is required.

ETA 1 day.

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
i am frontend developer ,Given my experience with smart contract development and event handling, I am well-equipped to implement these changes effectively

### How I plan on tackling this issue
To address the issue of ensuring that relevant data is captured in the events, I would first review the current event emission functionality within the codebase to identify where improvements can be made. I would then determine the specific data attributes that are necessary for each event based on the project requirements and ensure they are included in the event struct. 

Next, I would implement the changes needed to capture this data during the event emission process. After that, I would write comprehensive unit tests to validate that the events are emitted with the correct data and that all relevant scenarios are covered. 
I anticipate completing this task within [3 to 5 working days based on your assessment].

**Comment by jsanchez556** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
Hello, I’m Jose Mario from Costa Rica. With over 15 years of experience in development, I am passionate about contributing to open-source projects and currently expanding my skill set with Rust, Cairo, and Solidity, participated in ODHacks since 7.0 as part of my involvement with Dojo Coding. I am eager to apply my extensive experience and newly acquired skills to new challenges and innovative projects.

### How I plan on tackling this issue
1. Define a new event that will be emitted when a product is verified. This should be done within the Product module(onchain/src/product/product.cairo)
2. Modify the verify function to emit the ProductVerified event when a product is verified successfully.

**Comment by aniruddhaaps** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
I am a python dev. A new-comer here, willing and ready to contribute to contribute to solve the issue.

**Comment by suhas-sensei** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
i am a blockchain dev and have prior experience in cairo

### How I plan on tackling this issue
i will upgrade Contracts to Cairo 2.8.4 as requested.

**Comment by EjembiEmmanuel** [comment]
@manlikeHB  I've assigned you. This issue depends on #3, so you can begin work as soon as it is completed.

**Comment by EjembiEmmanuel** [comment]
@manlikeHB  this issue is now open as #3has been completed.
